name: Build, Upload Release, and Sync with SVN

on:
    release:
        types:
            - created
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build_upload_sync:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'

            -   name: Install Mozart globally
                run: composer global require --no-progress --no-interaction coenjacobs/mozart

            -   name: Install prod deps & compile
                run: |
                    composer install --no-dev --optimize-autoloader --no-interaction --no-scripts
                    "$(composer global config home --quiet)/vendor/bin/mozart" compose
                    composer dump-autoload -o

            -   name: Get Release Version
                id: get_version
                run: |
                    RELEASE_VERSION=$(grep "^Stable tag:" readme.txt | awk -F' ' '{print $NF}')
                    echo "Release Version: $RELEASE_VERSION"
                    echo "version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

                # Step 6: Install Subversion (SVN)
            -   name: Install Subversion
                run: sudo apt-get update --allow-releaseinfo-change && sudo apt-get install -y subversion

            -   name: Sync with SVN on Release
                env:
                    SVN_USERNAME: ${{ secrets.SVN_REP_USER }}
                    SVN_PASSWORD: ${{ secrets.SVN_REP_PW }}
                run: |
                    set -euo pipefail

                    RELEASE_VERSION=${{ steps.get_version.outputs.version }}
                    if [ -z "$RELEASE_VERSION" ]; then
                        echo "Error: RELEASE_VERSION is empty. Ensure readme.txt contains a 'Stable tag:' line and the previous step exported it."
                        exit 1
                    fi
                    echo "version: $RELEASE_VERSION"

                    SVN_URL="https://plugins.svn.wordpress.org/wc-buckaroo-bpe-gateway"
                    WORKDIR="$HOME/tmp"
                    mkdir -p "$WORKDIR"
                    cd "$WORKDIR"

                    # Shallow checkout root, then fully fetch trunk and assets
                    svn checkout --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache \
                        --non-interactive --trust-server-cert --depth immediates "$SVN_URL" wc-buckaroo-bpe-gateway
                    cd wc-buckaroo-bpe-gateway
                    svn update trunk --set-depth infinity || true
                    if [ -d assets ]; then
                        svn update assets --set-depth infinity || true
                    else
                        mkdir -p assets
                        svn add assets || true
                    fi

                    # Mirror repository to trunk without nuking it
                    rsync -a --delete --delete-excluded \
                        --exclude='.git' --exclude='.github' --exclude='.wordpress-org' \
                        "${{ github.workspace }}/" trunk/

                    # Sync wordpress.org assets if present
                    if [ -d "${{ github.workspace }}/.wordpress-org" ]; then
                        rsync -a --delete --delete-excluded "${{ github.workspace }}/.wordpress-org/" assets/
                    fi

                    # Stage changes precisely
                    svn add --force trunk assets 2>/dev/null || true
                    svn status --ignore-externals | grep -E "^\!" | sed -E 's/^\![[:space:]]+//' | while IFS= read -r f; do
                        svn rm --force "$f"
                    done || true

                    # Commit once, like the original flow
                    if svn status | grep -qE '^[MADRC]'; then
                        svn commit \
                            --config-option servers:global:http-timeout=3600 \
                            --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache \
                            --non-interactive --trust-server-cert \
                            -m "release $RELEASE_VERSION"
                    else
                        echo "No changes to commit"
                    fi

                    # Tag using server-side copy
                    svn copy \
                        --config-option servers:global:http-timeout=3600 \
                        --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache \
                        --non-interactive --trust-server-cert \
                        "$SVN_URL/trunk" "$SVN_URL/tags/$RELEASE_VERSION" \
                        -m "release $RELEASE_VERSION"

                    echo "SVN sync completed successfully for version: $RELEASE_VERSION"

            -   name: Package Plugin
                run: |
                    rsync -av --exclude='.git' --exclude='.github' --exclude='.wordpress-org' ./* "wc-buckaroo-bpe-gateway/"
                    zip -r "wc-buckaroo-bpe-gateway.zip" "wc-buckaroo-bpe-gateway"

            -   name: Upload Asset to Release
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: ./wc-buckaroo-bpe-gateway.zip
                    asset_name: wc-buckaroo-bpe-gateway.zip
                    asset_content_type: application/zip
