name: PHP Compatibility Check

on:
    pull_request:
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: [ '7.4', '8.0', '8.1', '8.2', '8.3', '8.4' ]

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP 8.2 for Mozart
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    tools: composer:v2
                    coverage: none

            -   name: Install composer & compile
                run: |
                    composer install --no-dev --optimize-autoloader --no-interaction --no-scripts
                    composer compose-dependencies
                    composer dump-autoload -o

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    tools: composer:v2
                    coverage: none

            -   name: Check PHP Compatibility
                run: composer require --dev --no-scripts php-parallel-lint/php-parallel-lint && vendor/bin/parallel-lint . --exclude vendor --exclude tools
